/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gmail.arthurstrokov.aop;

import com.gmail.arthurstrokov.aop.service.FakeService;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class FakeServiceTest {
    @Test
    public void someLibraryMethodReturnsTrue() {
        FakeService classUnderTest = new FakeService();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someFakeMethod());
    }
}
