/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gmail.arthurstrokov.aop.service;

import com.gmail.arthurstrokov.aop.annotations.Countable;
import com.gmail.arthurstrokov.aop.annotations.TrackTime;
import org.springframework.stereotype.Service;

@Service
public class FakeService {
    @TrackTime
    @Countable
    public boolean someFakeMethod() {
        return true;
    }
}
